name: Release to Chrome Web Store
on:
  push:
    branches:
      - master
    paths:
      - 'manifest.json'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Zip and publish
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install
      - run: npm run zip
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-file
          path: build.zip